DB-3614: support passing optional parameters to the connection by usi…
newrelic/nri-mysql pull request #88
Opened 2021-06-16 21:26 UTC by brybry192

…ng flag -connection_parameters tls=skip-verify&timeout=5s

Hi 👋, we require TLS support for all database connections in AWS, so I'm making a quick change to support passing in optional connection parameters to the Go MySQL driver. Please see https://github.com/go-sql-driver/mysql#parameters for more info on the supported connection parameters. 

Example Invocation using the -connection_parameters to use a TLS connection, but not verify the certificate and set a timeout for it:
```
./nri-mysql -hostname db-depot.cluster-cl3aokvievxs.us-east-2.rds.amazonaws.com -database db_depot -port 3306 -username $u -password $p -connection_parameters "tls=skip-verify&timeout=5s"
```

This should address a recent issue https://github.com/newrelic/nri-mysql/issues/87 too.

For instance, to support encryption on an RDS instance and verify the certificate we will need to import their bundle first. See https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html for further information and link to download their bundle.

I'm using an alpine container here with newrelic-infra running in it:
```
/ # cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.4
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

Here's a failure case using nri-mysql that includes `tls=true` to verify the certificate used for the TLS connection. It fails since we do not have the certificate imported into the standard system CA locations the Go x509 package searches by default:
```
/ # ./nri-mysql hostname db-depot.cluster-cl3aokvievxs.us-east-2.rds.amazonaws.com -database db_depot -port 3306 -username $u -password $p -connection_parameters "tls=true&timeout=5s"
[FATAL] can't continue: error querying inventory: error executing `SHOW GLOBAL VARIABLES`: x509: certificate signed by unknown authority
```

This alpine image has ca-certificates already installed, so we can download the AWS global bundle, place in the proper location and run update-ca-certificates:
```
/ # wget https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
Connecting to truststore.pki.rds.amazonaws.com (52.84.145.100:443)
global-bundle.pem    100% |***********************************************************************************************************************************************************************************************|   146k  0:00:00 ETA
/ # mv global-bundle.pem /usr/local/share/ca-certificates/
/ # update-ca-certificates
```

re-running nri-mysql test case and printing first 128 bytes:
```
/ # ./nri-mysql -hostname db-depot.cluster-cl3aokvievxs.us-east-2.rds.amazonaws.com -database db_depot -port 3306 -username $u -password $p -connection_parameters "tls=true&timeout=5s" | head -c 128; echo
{"name":"com.newrelic.mysql","protocol_version":"3","integration_version":"0.0.0","data":[{"metrics":[{"cluster.nodeType":"maste
```

2021-06-16 21:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/nri-mysql?pullRequest=88) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/nri-mysql?pullRequest=88) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/nri-mysql?pullRequest=88) it.</sub>

2021-06-17 11:04 UTC, ivancorrales reviewed
Hey @brybry192  thanks for your PR, would you mind renaming the property `ConnectionParameters` to. `ExtraConnectionURLArgs`? Just to be consistent with other New Relic integrations with a similar approach

Thanks!

2021-06-17 15:23 UTC, brybry192 commented
Thank you! I've pushed the change and updated the notes above to use `-extra_connection_url_args`.

2021-06-18 07:10 UTC, ivancorrales approved these changes
It looks good to me!
Thanks!

2021-06-18 08:07 UTC, roobre requested changes
I think `InsecureSkipVerify` is usually relevant enough to give it it's own option, I would be happier having it as a dedicated parameter in the argument list.

Regarding `ExtraConnectionURLArgs`, I think this is a great feature! I would however suggest to, rather than using `strings.Split` and append for handling the URL parameters, parsing and appending them into `url.Values` instead. Something very similar can be found here:

https://github.com/newrelic/nri-mssql/blob/bbf0555731df8e6b3bc88518cd0a99ecc86bf0c8/src/connection/sql_connection.go#L54

2021-06-20 04:47 UTC, brybry192 commented
Updates have been made. `-enable_tls` and `-insecure_skip_verify` are options now:
```
Bryants-MBP:src bryant$ ./nri-mysql -hostname localhost -username $u -password $p -enable_tls  | head -c 128; echo
[FATAL] can't continue: error querying inventory: error executing `SHOW GLOBAL VARIABLES`: x509: certificate is not valid for any names, but wanted to match localhost

Bryants-MBP:src bryant$ ./nri-mysql -hostname localhost -username $u -password $p -insecure_skip_verify  | head -c 128; echo
{"name":"com.newrelic.mysql","protocol_version":"3","integration_version":"0.0.0","data":[{"metrics":[{"cluster.nodeType":"maste
```

2021-06-20 04:48 UTC, brybry192 commented on src/mysql.go
> +	ExtraConnectionURLArgs string `help:"Specify extra connection parameters as attribute=value."` // https://github.com/go-sql-driver/mysql#parameters
Great suggestions! Thank you.

2021-06-25 09:40 UTC, roobre commented
Thanks for the changes @brybry192, they look great at first glance!
This week I'm on PTO but somebody from the team will take a deeper look as soon as they can :)

2021-06-30 11:55 UTC, roobre approved these changes
LGTM, many thanks for your contribution!

2021-06-30 11:57 UTC, merged